/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Igu;

import Logica.Persona;
import Persistencia.Archivo;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Caro
 */
public class DialogContactos extends javax.swing.JDialog {
    
    /**
     * Creates new form DialogContactos
     */
    public DialogContactos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.mostrar();
    }

    public void mostrar(){
        List<String> lista = new ArrayList<String>();
        Archivo datos = new Archivo();
        
        //abro el archivo y llamo al metodo que me trae todos los registros en una lista
        datos.crearArchivo();
        lista = datos.leerTodosLosRegistros();
        
        //recupero cada item con un iterador
        Iterator iter = lista.iterator();
        
        //recorro pasando todo a una matriz para cargarlo en la tabla
        int control = lista.size();
        int tama = lista.size();
        int cantReg = control / 4;
        int controlReg = 0;
        String matriz[][] = new String[lista.size()][4];
        int fil = 0;
        int col = 0;
        
        //prueba
        
        tableTabla.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Dirección"
            }));
        ///fin prueba
        
        
        while(iter.hasNext() && fil < lista.size() && controlReg<=cantReg){ //recorro para obtener e imprimir los datos
            matriz[fil][col] = iter.next().toString();
            tableTabla.setValueAt(matriz[fil][col], fil, col);
            col++;
            matriz[fil][col] = iter.next().toString();
            tableTabla.setValueAt(matriz[fil][col], fil, col);
            col++;
            matriz[fil][col] = iter.next().toString();
            tableTabla.setValueAt(matriz[fil][col], fil, col);
            col++;
            matriz[fil][col] = iter.next().toString();
            tableTabla.setValueAt(matriz[fil][col], fil, col);
            col= 0;
            fil++;
            
            
            
        }
        
   
        /*
        tableTabla.setModel(new javax.swing.table.DefaultTableModel(
                lista(), 
                new String [] 
                {"Nombre", "Apellido", "Teléfono", "Dirección"})); */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPaneContactos = new javax.swing.JScrollPane();
        tableTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tableTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneContactos.setViewportView(tableTabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPaneContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPaneContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPaneContactos;
    private javax.swing.JTable tableTabla;
    // End of variables declaration//GEN-END:variables
}
