//ventana principal del programa

package Igu;

public class FormPrincipal extends javax.swing.JFrame {
    DialogAniadir aniadir = new DialogAniadir(this, true);
    DialogContactos contactos = new DialogContactos(this, true);
    
    public FormPrincipal() {
        initComponents();
        setTitle("MiniAgenda");
        aniadir.setVisible(false);
        contactos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        MnuVerContactos = new javax.swing.JMenu();
        MnuAniadirContacto = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        MnuVerContactos.setText("Ver contactos");
        MnuVerContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuVerContactosMouseClicked(evt);
            }
        });
        Menu.add(MnuVerContactos);

        MnuAniadirContacto.setText("Añadir contacto");
        MnuAniadirContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuAniadirContactoMouseClicked(evt);
            }
        });
        Menu.add(MnuAniadirContacto);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAniadirContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuAniadirContactoMouseClicked
        //Crear y hacer visible el formulario
        aniadir.setVisible(true);
        contactos.mostrar();
        
        
    }//GEN-LAST:event_MnuAniadirContactoMouseClicked

    private void MnuVerContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuVerContactosMouseClicked
        contactos.setVisible(true);
        contactos.mostrar();
    }//GEN-LAST:event_MnuVerContactosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MnuAniadirContacto;
    private javax.swing.JMenu MnuVerContactos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
